#!/bin/bash

# Check for button clicks
if [ -n "${BLOCK_BUTTON}" ]
then
	IFS=$'\n'
	info=($(battery -i))
	notify-send -t 7000 --icon=battery -- "${info[0]}" "${info[*]:1}"
fi

# Get battery level
nobattery="N/A"
bat=$(battery -S)
value="${bat%%\%*}" 
status=$(echo "${bat##*\(}" | tr -d ')')

# Get color
color="#ffffff"

if [ "${status}" == "Charging" ]
then
	color="#00bfff"
elif ! [ "${value}" -eq "${value}" ] 2> /dev/null
then
	value="${nobattery}"
	color="#b2b2b2"
elif [ "${value}" -le 30 ]
then
	color="#ff0000"
elif [ "${value}" -le 50 ]
then
	color="#ffa500"
elif [ "${value}" -le 70 ]
then
	color="#ffff00"
else
	:
fi

# Add percent sign
if [ "${value}" != "${nobattery}" ]
then
	value="${value}%"
	echo "  <span color='${color}' font='monospace'>${value}</span>  "
	echo "  <span color='${color}' font='monospace'>${value}</span>  "
	echo 
fi
