#!/bin/bash

# Check for button clicks
if [ -n "${BLOCK_BUTTON}" ]
then
	aria --title="$(battery -i)" --time=5 > /dev/null
fi

# Get battery level
bat=$(battery -S)
int="${bat%%\%*}" 
status=$(echo "${bat##*\(}" | tr -d ')')

# Get color
color="#ffffff"

if [ "${status}" == "Charging" ]
then
	color="#00bfff"
elif [ "${int}" -le 30 ]
then
	color="#ff0000"
elif [ "${int}" -le 50 ]
then
	color="#ffa500"
elif [ "${int}" -le 70 ]
then
	color="#ffff00"
else
	:
fi

echo "<span color='${color}' font='monospace'>${int}% </span>"
echo "<span color='${color}' font='monospace'>${int}% </span>"
echo 
