#!/bin/bash

# Check for button clicks
if [ -n "${BLOCK_BUTTON}" ]
then
	notify-send -t 4000 --icon=display-brightness "$(bright)"
fi

# Get brightness level
bright=$(bright -S)

if [ "${bright}" != "N/A" ]
then
	echo "  <span font='monospace'>${bright}</span>  "
	echo "  <span font='monospace'>${bright}</span>  "
	echo 
fi
