#!/bin/bash

# Check for button clicks
if [ -n "${BLOCK_BUTTON}" ]
then
	aria --title="$(bright)" > /dev/null
fi

# Get brightness level
bright=$(bright -S)

if [ "${bright}" != "N/A" ]
then
	echo "  <span font='monospace'>${bright} </span>"
	echo "  <span font='monospace'>${bright} </span>"
	echo 
fi
