#!/bin/bash

# Check for button clicks
if [ -n "${BLOCK_BUTTON}" ]
then
	gsimplecal &
	exit 0
fi

# Get date and time
string=$(date +"%a %B %-d %-I:%M:%S %p")

echo "<span font='monospace'>${string} </span>"
echo "<span font='monospace'>${string} </span>"
echo 
