#!/bin/bash

# Check for clicks
if [ -n "${BLOCK_BUTTON}" ]
then
	aria --title="$(vol)" > /dev/null
fi

# Get volume level
vol=$(vol -S)

echo "<span font='monospace'>${vol} </span>"
echo "<span font='monospace'>${vol} </span>"
echo 
