#!/bin/bash

color=
symbol=

if [ -d /sys/class/net/tun0 ]
then
	color="#109910"
	symbol=""
else
	color="#ff0000"
	symbol=""
fi

echo "<span color='${color}' font='monospace'>${symbol}</span>"
echo "<span color='${color}' font='monospace'>${symbol}</span>"
echo 
