#!/bin/bash

status=
color=

if [ -d /sys/class/net/tun0 ]
then
	status="UP"
	color="#1bff1b"
else
	status="DOWN"
	color="#ff0000"
fi

echo "<span color='${color}' font='monospace'>${status} </span>"
echo "<span color='${color}' font='monospace'>${status} </span>"
echo 
