#!/bin/bash

# Check for button clicks
if [ -n "${BLOCK_BUTTON}" ]
then
	aria --title="$(wifi -p)" --time=4 > /dev/null
fi

# Get wifi info
info=$(wifi)
int=$(echo "${info:$[${#info}-6]}" | cut -f2 -d'(' | cut -f1 -d'%')
color=

if [ "${info:0:3}" == ":: " ]
then
	info="${info:3:-1}"
	color="#00bfff"
fi

echo "<span font='monospace'>${info} </span>"
echo "<span font='monospace'>${info} </span>"

# Get color
if [ -n "${color}" ]
then
	:
elif [ "${int}" -le 50 ]
then
	color="#ff0000"
elif [ "${int}" -le 70 ]
then
	color="#ffff00"
else
	:
fi

echo "${color}"
