#!/bin/bash

# Check for button clicks
if [ -n "${BLOCK_BUTTON}" ]
then
	aria --title="$(wifi -p)" --time=4 > /dev/null
fi

# Get wifi info
info=$(wifi)
int=$(echo "${info:$[${#info}-6]}" | cut -f2 -d'(' | cut -f1 -d'%')
color="#ffffff"
alarm="#ff0000"

if [ "${info:0:3}" == ":: " ]
then
	info="${info:3:-1}"
	color="${alarm}"
fi

# Get color
if [ "${color}" == "${alarm}" ]
then
	:
elif [ "${int}" -le 50 ]
then
	color="#ffff00"
elif [ "${int}" -le 70 ]
then
	color="#ffff00"
else
	:
fi

echo "<span color='${color}' font='monospace'>${info} </span>"
echo "<span color='${color}' font='monospace'>${info} </span>"
echo 
